#
# Copyright (c) 2023, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#

apiVersion: database.oracle.com/v1alpha1
kind: DataguardBroker
metadata:
  name: dataguardbroker-sample
  namespace: default
spec:
  
  ## Primary DB ref. This is of kind SingleInstanceDatabase
  primaryDatabaseRef: "sidb-sample"

  ## Standby DB pod CRD Metadata Name to add this DB to DG config
  standbyDatabaseRefs:
  #  - standbydatabase-sample
  #  - standbydatabase-sample1

  ## Type of service . Applicable on cloud enviroments only
  ## if loadBalService : false , service type = "NodePort" . else "LoadBalancer"
  loadBalancer: false

  ## Protection Mode for dg configuration . MaxAvailability or MaxPerformance
  protectionMode: MaxAvailability

  ## Specify the database SID to switchover thereby making it the primary.
  ## Switchover is not supported when fastStartFailover is true.
  setAsPrimaryDatabase: ""

  ## Enable/disable Fast-Start Failover for the dataguard configuration.
  fastStartFailover: false
