#
# Copyright (c) 2021, Oracle and/or its affiliates. 
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#

apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  oracle_pwd: "Change_On_Install_1"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: sidb-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  storageClassName: sidb
  hostPath:
    path: /data/oradata
  
---

apiVersion: database.oracle.com/v1alpha1
kind: SingleInstanceDatabase
metadata:
  name: sidb-sample
  namespace: default
spec:
  
  ## Use only alphanumeric characters for sid
  sid: ORCL1
  
  ## A source database ref to clone from, leave empty to create a fresh database
  cloneFrom: ""

  ## NA if cloning from a SourceDB (cloneFrom is set)
  edition: enterprise
  
  ## Should refer to SourceDB secret if cloning from a SourceDB (cloneFrom is set)
  ## Secret containing SIDB password mapped to secretKey
  ## This secret will be deleted after creation of the database unless keepSecret is set to true
  adminPassword:
    secretName: db-secret
    secretKey: oracle_pwd
    keepSecret: false

  ## NA if cloning from a SourceDB (cloneFrom is set)
  charset: AL32UTF8

  ## NA if cloning from a SourceDB (cloneFrom is set)
  pdbName: orclpdb1

  ## Enable/Disable Flashback
  flashBack: false

  ## Enable/Disable ArchiveLog
  archiveLog: false

  ## Enable/Disable ForceLogging
  forceLog: false

  ## NA if cloning from a SourceDB (cloneFrom is set)
  ## Specify both sgaSize and pgaSize (in MB) or dont specify both
  ## Specify Non-Zero value to use
  initParams:
    cpuCount: 0
    processes: 0
    sgaTarget: 0
    pgaAggregateTarget: 0

  ## Database image details
  ## Database can be patched by updating the RU version/image
  ## Major version changes are not supported
  image:
    pullFrom:
    pullSecrets:

  ## size : Minimum size of pvc | class : PVC storage Class
  ## AccessMode can only accept one of ReadWriteOnce, ReadWriteMany
  persistence:
    size: 4Gi
    storageClass: "sidb"
    accessMode: "ReadWriteMany"

  ## Count of Database Pods. Applicable only for "ReadWriteMany" AccessMode
  replicas: 1
