#
# Copyright (c) 2021, Oracle and/or its affiliates. 
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#
apiVersion: database.oracle.com/v1alpha1
kind: SingleInstanceDatabase
metadata:
  name: sidb-sample
  namespace: default
spec:
  
  ## Use only alphanumeric characters for sid
  sid: ORCL1

  ## Secret containing SIDB password mapped to secretKey 
  adminPassword:
    secretName: 
    secretKey:
    keepSecret: false

  ## Database image details
  image:
    pullFrom:
    pullSecrets:

  ## size : Minimum size of pvc | class : PVC storage Class
  ## AccessMode can only accept one of ReadWriteOnce, ReadWriteMany
  ## Below mentioned storageClass/accessMode applies to OCI block volumes. Update appropriately for other types for persistent volumes.
  persistence:
    size: 100Gi
    storageClass: "oci"
    accessMode: "ReadWriteOnce"

  ## Count of Database Pods. Applicable only for "ReadWriteMany" AccessMode
  replicas: 1
