# This rule is not used by the project oracle-database-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over privateai.oracle.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: oracle-database-operator
    app.kubernetes.io/managed-by: kustomize
  name: privateai-privateai-admin-role
rules:
- apiGroups:
  - privateai.oracle.com
  resources:
  - privateais
  verbs:
  - '*'
- apiGroups:
  - privateai.oracle.com
  resources:
  - privateais/status
  verbs:
  - get
