# This rule is not used by the project oracle-database-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the privateai.oracle.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: oracle-database-operator
    app.kubernetes.io/managed-by: kustomize
  name: privateai-privateai-editor-role
rules:
- apiGroups:
  - privateai.oracle.com
  resources:
  - privateais
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - privateai.oracle.com
  resources:
  - privateais/status
  verbs:
  - get
