# permissions for end users to view racdatabases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: racdatabase-viewer-role
rules:
- apiGroups:
  - database.oracle.com
  resources:
  - racdatabases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - database.oracle.com
  resources:
  - racdatabases/status
  verbs:
  - get
