apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: racdatabases.database.oracle.com
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        caBundle: Cg==
        service:
          namespace: oracle-database-operator-system
          name: oracle-database-operator-webhook-service
          path: /convert
      conversionReviewVersions:
        - v1
        - v1beta1
        - v4
