#
# Copyright (c) 2022, Oracle and/or its affiliates. 
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#
apiVersion: database.oracle.com/v4
kind: AutonomousDatabaseBackup
metadata:
  name: autonomousdatabasebackup-sample
spec:
  # Before you can create on-demand backups, you must have an Object Storage bucket and your database must be configured to connect to it. This is a one-time operation.
  # See https://docs.oracle.com/en-us/iaas/Content/Database/Tasks/adbbackingup.htm#creatingbucket
  target:
    k8sADB:
      name: autonomousdatabase-sample
    # # Uncomment the below block if you use ADB OCID as the input of the target ADB
    # ociADB:
    #   ocid: ocid1.autonomousdatabase...
  displayName: autonomousdatabasebackup-sample
  isLongTermBackup: true
  retentionPeriodInDays: 90 # minimum retention period is 90 days
  
  # Authorize the operator with API signing key pair. Comment out the ociConfig fields if your nodes are already authorized with instance principal.
  ociConfig:
    configMapName: oci-cred
    secretName: oci-privatekey